name: publish release
on: [ workflow_dispatch ]

jobs:
  publish:
    needs: [ build ]
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          java: 21
